### ISSUE TITLE
Homebridge not remembering light states

### ISSUE THREAD

**Issue by Cardo1** [rooi/homebridge-lightwaverf#23] opened 2017-01-15 17:56 UTC
For the past few weeks, I've noticed Homebridge doesn't remember the state of most of my lights.  I appreciate LightwaveRF can't confirm the actual state of any switch, but it used to remember the last state they were set to through HomeKit.  However, now it only seems to remember a specific 3 or 4 lights, and all the others it always thinks are off.

Is the state of the lights part of the Lightwaverf plugin or Homebridge itself?

**Comment by JangoBritt** [comment] 2017-01-19 14:43
I wonder if ON/OFF could use R1D1F1/R1D1F0, rather than R1D1FdP32, to switch ON a dimmer... would that remember the previous state?

**Comment by rooi** [comment] 2017-02-18 08:29
Hi,

Just came back from holiday... I noticed the same issue and will try to fix it soon.

Roy

**Comment by andygroves** [comment] 2017-02-20 16:37
Dear Sirs,

I also had the same issue.

Can I ask also, will the garage door function ad different functionality, or is there a more detailed manual.

Can I also ask, is there an thoughts or possibility of adding the heating devices to the app.

Im more than willing to beta test any developments.

Best regards,

Andy Groves.

**Comment by neameo** [comment] 2017-12-17 19:27
Hi,

Sorry to bump an old thread.... Did this ever get fixed for the others in this thread?

I have just been forced to do a fresh install of Homebridge & the Lightwave plugin (won't go into it!) - since doing so all of my dimmer switches remember their states within the Home app, but sockets no longer do, as described by the OP. All my devices remembered states in the home app prior to the fresh install.

I know the install will be running newer versions of Node, Homebridge & probably Lightwave since the rebuild and wanted to know if a downgrade would fix this. 

I'm guessing its something to do with the dimming command as all my switches are dimmers (and they are still fine) and all other sockets no longer work.

Annoyingly I didn't make a note of the "working" versions that I had installed prior to the fresh build

If anyone has a fix, or knows which versions to downgrade to to enable this please let me know - its driving me mad

Thanks

**Comment by leonbarrett** [comment] 2017-12-21 18:37
+1 for the previous post. I did a fresh install and states are no longer remembered

**Comment by rooi** [comment] 2017-12-22 07:24
Thanks for bringing this back to my attention. Should be fixed in commit today, but please test and notify me again if it does not work

**Comment by neameo** [comment] 2018-01-01 22:03
Hi Roy,

It’s taken me a while to get upgraded to 0.1.5 

I can confirm switch/light/dimmer states are all remembered in the home app again after the upgrade.

Big thanks for resolving so quickly

**Comment by rooi** [comment] 2018-01-02 05:04
Great!

**Closed as completed by rooi** 2018-01-02 05:04 UTC
